# This file has been autogenerated by ts2gd. DO NOT EDIT!

extends Node
class_name GlobalHelper

var BackgroundAudio setget , BackgroundAudio_get
var lastSceneSnapshot = null
var lastSceneLayer = null
var lastScene = null
func BackgroundAudio_get():
  return self.get_node("/root/Audio")
