# This file has been autogenerated by ts2gd. DO NOT EDIT!


extends Node2D
class_name Pause







var Overlay : get = Overlay_get
func Overlay_get():
  return self.get_node("Overlay")
func _enter_tree():
  self.Overlay.visible = false
func _ready():
  self.Overlay.visible = false
func onPauseButtonPressed():
  self.get_viewport().set_input_as_handled()

