# This file has been autogenerated by ts2gd. DO NOT EDIT!


@tool
extends TextureButton
class_name SpeechBase







var LI : get = LI_get
@export var label: String : get = label_get, set = label_set
func LI_get():
  return self.get_node("Label") if self.has_node("Label") else null
func label_set(text: String):
  if self.LI:
    self.LI.text = text
func label_get():
  var __gen = self.LI
  return ((__gen.text if __gen != null else null) if ((__gen.text if __gen != null else null)) != null else "")

