# This file has been autogenerated by ts2gd. DO NOT EDIT!


extends Base
class_name About





var Base = load("res://scenes/Base.gd")


func onClose():
  self.switchTo("res://scenes/menu/Menu.tscn")

