# This file has been autogenerated by ts2gd. DO NOT EDIT!

extends Base
class_name Loading

var Timer setget , Timer_get
func Timer_get():
  return self.get_node("Timer")
func _ready():
  self.Timer.start()
func onTimerTimeout():
  self.switchTo("res://scenes/menu/Menu.tscn")
